# Generated by Django 6.0.6 on 2026-07-04 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Razón Social')),
                ('company_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('cuit', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, verbose_name='CUIT')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('industry', models.CharField(blank=True, max_length=150, verbose_name='Rubro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Localidad')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospecto'), ('QUALIFIED', 'Calificado'), ('CLIENT', 'Cliente'), ('INACTIVE', 'Inactivo')], default='PROSPECT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['status'], name='companies_c_status_2407e4_idx'), models.Index(fields=['industry'], name='companies_c_industr_6efa2c_idx'), models.Index(fields=['city'], name='companies_c_city_42f3fb_idx')],
            },
        ),
    ]
