# Generated by Django 6.0.6 on 2026-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
    ]
