# Generated by Django 6.0.6 on 2026-07-10 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('department', models.CharField(choices=[('MANAGEMENT', 'Gerencia'), ('HSE', 'Higiene y Seguridad'), ('HR', 'Recursos Humanos'), ('PURCHASING', 'Compras'), ('PRODUCTION', 'Producción'), ('MAINTENANCE', 'Mantenimiento'), ('QUALITY', 'Calidad'), ('ADMINISTRATION', 'Administración'), ('OTHER', 'Otro')], default='OTHER', max_length=30, verbose_name='Departamento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name'], name='contacts_co_last_na_12cfae_idx'), models.Index(fields=['department'], name='contacts_co_departm_5c1f17_idx')],
            },
        ),
    ]
