# Generated by Django 6.0.6 on 2026-07-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp',
        ),
    ]
