# Generated by Django 6.0.6 on 2026-07-06 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Contacto (nombre)')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Llamada'), ('EMAIL', 'Email'), ('MEETING', 'Reunión'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visita'), ('OTHER', 'Otro')], default='CALL', max_length=20, verbose_name='Tipo')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('outcome', models.CharField(blank=True, choices=[('POSITIVE', 'Positivo'), ('NEUTRAL', 'Neutro'), ('NEGATIVE', 'Negativo'), ('NO_RESPONSE', 'Sin respuesta')], max_length=20, verbose_name='Resultado')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Próximo seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', '-date'], name='interaction_company_7b31a0_idx'), models.Index(fields=['follow_up_date'], name='interaction_follow__2ae1df_idx')],
            },
        ),
    ]
