# Generated by Django 6.0.6 on 2026-07-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('GOOGLE_MAPS', 'Google Maps'), ('LINKEDIN', 'LinkedIn'), ('WEBSITE', 'Sitio web'), ('NEWSLETTER', 'Boletín'), ('CSV_IMPORT', 'Importación CSV/Excel'), ('MANUAL', 'Carga manual')], max_length=20, verbose_name='Fuente')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('cuit', models.CharField(blank=True, max_length=13, verbose_name='CUIT')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='Sitio Web')),
                ('industry', models.CharField(blank=True, max_length=150, verbose_name='Rubro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Localidad')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('NEEDS_REVIEW', 'Necesita revisión'), ('PROMOTED', 'Promovida a Company'), ('REJECTED', 'Rechazada')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_companies_created', to=settings.AUTH_USER_MODEL)),
                ('promoted_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_sources', to='companies.company')),
            ],
            options={
                'verbose_name': 'Empresa cruda (staging)',
                'verbose_name_plural': 'Empresas crudas (staging)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='scraping_ra_status_1a008b_idx'), models.Index(fields=['source'], name='scraping_ra_source_113cba_idx')],
            },
        ),
    ]
