# Generated by Django 6.0.6 on 2026-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcompany',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Correo Electrónico'),
        ),
    ]
