# Generated by Django 6.0.6 on 2026-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_rawcompany_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
    ]
