# Generated by Django 6.0.6 on 2026-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_rawcompany_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=300, verbose_name='Teléfono'),
        ),
    ]
